package com.bstapp.repository;

import com.bstapp.model.BstTree;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/*
 * These are tests for my repository layer - the part that talks to the database.
 * 
 * @DataJpaTest is a special annotation that:
 * - Only loads the JPA/database components (not the full app)
 * - Uses an in-memory H2 database for testing
 * - Rolls back transactions after each test (so tests don't affect each other)
 * 
 * TestEntityManager is like EntityManager but with extra testing utilities.
 * I use it to directly persist entities without going through my repository,
 * so I can test that my repository methods find them correctly.
 */
@DataJpaTest
class BstTreeRepositoryTest {
    
    // TestEntityManager for directly interacting with the database in tests
    @Autowired
    private TestEntityManager entityManager;
    
    // The repository I'm testing
    @Autowired
    private BstTreeRepository repository;
    
    /*
     * TEST 1: Can we save and retrieve a tree?
     * 
     * This is the most basic test - create a tree, save it, then
     * retrieve it and make sure all the data is correct.
     */
    @Test
    void testSaveAndFindTree() {
        // Create a new tree entity
        BstTree tree = new BstTree("[7, 3, 9]", "{\"value\":7,\"left\":{\"value\":3},\"right\":{\"value\":9}}");
        
        // Save it using TestEntityManager (bypassing the repository)
        entityManager.persist(tree);
        entityManager.flush();  // Force the SQL to execute immediately
        
        // Now use the repository to find all trees
        List<BstTree> trees = repository.findAll();
        
        // Check that we got our tree back with correct data
        assertEquals(1, trees.size());
        assertEquals("[7, 3, 9]", trees.get(0).getInputNumbers());
        assertNotNull(trees.get(0).getTreeJson());
        assertNotNull(trees.get(0).getCreatedAt());  // Should be auto-set
    }
    
    /*
     * TEST 2: Does the ordering work correctly?
     * 
     * My custom method findAllByOrderByCreatedAtDesc should return trees
     * with the most recently created first. This test creates two trees
     * with a small time gap and verifies the order.
     */
    @Test
    void testFindAllByOrderByCreatedAtDesc() throws InterruptedException {
        // Create first tree
        BstTree tree1 = new BstTree("[1, 2, 3]", "{\"value\":1}");
        entityManager.persist(tree1);
        entityManager.flush();
        
        // Wait a tiny bit so the timestamps are different
        // (LocalDateTime has nanosecond precision, but just to be safe)
        Thread.sleep(10);
        
        // Create second tree (newer)
        BstTree tree2 = new BstTree("[4, 5, 6]", "{\"value\":4}");
        entityManager.persist(tree2);
        entityManager.flush();
        
        // Get trees ordered by date descending
        List<BstTree> trees = repository.findAllByOrderByCreatedAtDesc();
        
        // Should have 2 trees
        assertEquals(2, trees.size());
        
        // The newer tree (tree2) should come first
        assertEquals("[4, 5, 6]", trees.get(0).getInputNumbers());
        assertEquals("[1, 2, 3]", trees.get(1).getInputNumbers());
    }
    
    /*
     * TEST 3: Is the ID auto-generated?
     * 
     * When I save a new tree, it shouldn't have an ID initially.
     * After saving, the database should assign an auto-incremented ID.
     */
    @Test
    void testAutoGeneratedId() {
        BstTree tree = new BstTree("[10, 20]", "{\"value\":10}");
        
        // Before saving, ID should be null
        assertNull(tree.getId());
        
        // Save the tree
        entityManager.persist(tree);
        entityManager.flush();
        
        // After saving, ID should be assigned and greater than 0
        assertNotNull(tree.getId());
        assertTrue(tree.getId() > 0);
    }
    
    /*
     * TEST 4: Can we delete a tree?
     * 
     * Tests the delete functionality. After deleting, the count should be 0.
     */
    @Test
    void testDeleteTree() {
        // Create and save a tree
        BstTree tree = new BstTree("[1]", "{\"value\":1}");
        entityManager.persist(tree);
        entityManager.flush();
        
        // Should have 1 tree
        assertEquals(1, repository.count());
        
        // Delete it
        repository.delete(tree);
        
        // Now should have 0 trees
        assertEquals(0, repository.count());
    }
    
    /*
     * TEST 5: Can we find a tree by its ID?
     * 
     * The findById method is inherited from JpaRepository.
     * This test verifies it works correctly.
     */
    @Test
    void testFindById() {
        // Create and save a tree
        BstTree tree = new BstTree("[5, 10, 15]", "{\"value\":5}");
        entityManager.persist(tree);
        entityManager.flush();
        
        // Get the auto-generated ID
        Long id = tree.getId();
        
        // Try to find by ID - should exist
        assertTrue(repository.findById(id).isPresent());
        
        // And the data should match
        assertEquals("[5, 10, 15]", repository.findById(id).get().getInputNumbers());
    }
}
